### ISSUE TITLE
Color parsing for the case of 24-bit color has hard-coded :foreground type

### ISSUE THREAD

**Issue by petrounias** [lambdaisland/ansi#3]
https://github.com/lambdaisland/ansi/blob/f55a5569f3fff95dd271e49b525aadbc1cac8cf5/src/lambdaisland/ansi.cljc#L131

This makes it impossible to use background CSI code 48. A change to ```{type (color-24-bit (take 3 more))}``` would most likely fix this.

**Comment by plexus** [comment]
Sounds good, a PR would be much appreciated. Are you building something with `lambdaisland/ansi`?

**Comment by plexus** [comment]
Released in 

```
[lambdaisland/ansi "0.2.37"]
{lambdaisland/ansi {:mvn/version "0.2.37"}}
```

seems this hadn't seen a release in a few years, I took the opportunity to modernize the setup a bit
- move to `main` as the main branch name
- use [lambdaisland/open-source](https://github.com/lambdaisland/open-source) tooling
